### ISSUE TITLE
Display mode for battery status

### ISSUE THREAD

**Issue by mkatter** [mkatter/openhab2-addons#4]
e.g. String item...

**Comment by Sbried** [comment]
+1

**Comment by cweitkamp** [comment]
@mkatter Nice work. Keep on going. If I can make a suggestion I would say the battery channel should have the item type Switch. OFF=battery_critcal=false, ON=battery_critical=true.
```
    <channel-type id="battery_low" advanced="true">
        <item-type>Switch</item-type>
        <label>Battery level low</label>
        <description>Indicates the current battery charge level ON=low, OFF=ok.</description>
        <category>Battery</category>
        <state readOnly="true"/>
    </channel-type>
```
If you need any help, don't hesitate to ask. I can write some lines of code if you like.

**Comment by mkatter** [comment]
@cweitkamp Thank you for your offer to help :)
I already implemented Eclipse Smart Home's system.low-battery channel a while ago.

Because of https://github.com/mkatter/openhab2-addons/issues/7 I actually did not want to commit but yesterday I did :)

**Comment by cweitkamp** [comment]
Nice.

**Comment by mkatter** [comment]
Done - see https://github.com/openhab/openhab2-addons/pull/2019/commits/330cf647406f151eee59ba2773f1741a7b1ff115
